import { ArrowUpRight, Heart, MessageCircle } from 'lucide-react';
import { SectionLabel } from '@/components/ui/SectionLabel';
import { Mascot, Crumb } from '@/components/brand/Mascot';
export function Lore() {
  return <section id="lore" className="lore section-space wrap" aria-labelledby="lore-title">
    <SectionLabel number="05">RECOVERED FROM THE GROUP CHAT</SectionLabel><div className="section-heading-row" data-reveal><h2 id="lore-title" className="section-title">THE LORE<br />IS <span className="hand-underline">GETTING WEIRD.</span></h2><p>A few pages from the bird brain.<br />Take a meme. Leave a crumb.</p></div>
    <div className="lore-collage">
      <article className="lore-card lore-poster" data-tilt data-reveal><span className="tape" /><div className="lore-poster-label mono">FIELD NOTE 001</div><h3>THEY SAID<br />TOUCH GRASS.</h3><div className="lore-bird"><Mascot mood="normal" /></div><div className="poster-grass" aria-hidden="true" /><strong className="poster-bottom">I ATE THE BREAD.</strong><button className="lore-save icon-button" type="button" data-download-poster="grass" aria-label="Save the Touch Grass meme"><ArrowUpRight size={19} /></button></article>
      <div className="lore-middle"><article className="lore-note" data-reveal><span className="note-pin" /><span className="mono">AN IMPORTANT REMINDER</span><p>you don&apos;t need<br />to have it all<br />figured out.<br /><u>be a bird.</u></p><span className="handwritten">— crumb, probably</span><Crumb className="note-crumb" /></article><article className="lore-message" data-reveal><div className="message-author"><span className="small-bird-avatar"><Mascot compact /></span><div><strong>crumb</strong><span className="mono">EXCERPT FROM THE FICTIONAL BIRD DIARY</span></div></div><p>my portfolio is just 3 crumbs<br />and an emotional attachment<br />to this website</p><div className="message-actions"><button type="button" data-like aria-pressed="false"><Heart size={18} /><span>Relatable</span></button><button type="button" data-copy-joke><MessageCircle size={18} /><span>Steal this line</span></button></div></article></div>
      <article className="lore-card lore-coo" data-tilt data-reveal><div className="coo-caption mono">DAILY AFFIRMATION</div><div className="coo-sticker">COO.<br />COO.<br /><span>COO.</span></div><div className="coo-bird"><Mascot compact mood="degen" /></div><p>Translation:<br /><strong>we are so back.</strong></p><button className="lore-save icon-button" type="button" data-download-poster="coo" aria-label="Save the Coo Coo meme"><ArrowUpRight size={19} /></button></article>
    </div><div className="lore-footer"><span className="handwritten">no thoughts. just crumbs.</span><a href="#gallery" className="text-link">Find your bird personality <ArrowUpRight size={18} /></a></div>
  </section>;
}
