import { ArrowUpRight, Copy, Check } from 'lucide-react';
import { Logo } from '@/components/brand/Logo';
import { BirdIcon } from '@/components/brand/Mascot';
import { Socials } from '@/components/ui/Socials';
import { site } from '@/lib/config';

export function Footer() {
  return <footer className="footer"><div className="wrap"><div className="footer-top"><div className="footer-brand"><a href="#home" aria-label="CRUMB home"><Logo /></a><p>Small bird. Big crumb energy.<br />An internet thing, with feathers.</p></div><nav aria-label="Footer navigation"><a href="#about">The bird</a><a href="#token">The token</a><a href="#roadmap">Flight plan</a><a href="#community">The flock</a></nav><div className="footer-social"><span className="mono">SAME BIRD. DIFFERENT NESTS.</span><Socials extended /></div></div><div className="footer-contract"><span className="mono">CHAIN: {site.chain || 'ROBINHOOD CHAIN'}</span><a href={site.ponsUrl} target="_blank" rel="noopener noreferrer" className="footer-ca-link" title="Open on Pons Family"><code>CA: {site.contract || 'Not announced'}</code><ArrowUpRight size={13} /></a>{site.contract && <button type="button" className="copy-button footer-copy-button" data-copy-contract aria-label="Copy contract address"><Copy className="copy-default" size={13} /><Check className="copy-success" size={13} /><span data-copy-label>Copy</span></button>}<a href={site.ponsUrl} target="_blank" rel="noopener noreferrer" className="text-link">Pons Family <ArrowUpRight size={15} /></a></div><div className="footer-disclaimer"><strong>A NOTE BEFORE YOU PECK.</strong><p>CRUMB is an original meme-brand concept, not a currently verified token launch. Meme tokens can lose all value. This website provides entertainment and information, not financial advice. Do not send funds to unverified contracts, trust unsolicited messages, or share your seed phrase. Proposed allocations and roadmap items are illustrative, not commitments. No affiliation with another token using a similar name is implied.</p></div><div className="footer-bottom"><span className="mono">© {new Date().getUTCFullYear()} CRUMB. MADE FOR THE FLOCK.</span><span className="footer-coo"><BirdIcon />keep it crumby.</span><a href="#home" className="mono">BACK TO THE ROOFTOP <ArrowUpRight size={15} /></a></div></div></footer>;
}
