import json, os
from pathlib import Path
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1]
OUTPUT=ROOT/'.local-qa'
OUTPUT.mkdir(exist_ok=True)
HTML=(ROOT/'preview/index.html').read_text()
results=[]
def check(name, ok, detail=None):
    results.append({'name':name,'passed':bool(ok),'detail':detail})
    print(('PASS' if ok else 'FAIL'), name, detail if detail else '')
with sync_playwright() as p:
    browser=p.chromium.launch(executable_path=os.environ.get('CHROMIUM_PATH') or None,headless=True,args=['--no-sandbox','--disable-dev-shm-usage'])
    ctx=browser.new_context(viewport={'width':1440,'height':1000},accept_downloads=True,reduced_motion='reduce')
    page=ctx.new_page(); page.set_default_timeout(5000); errors=[]
    page.on('pageerror',lambda e:errors.append(str(e)))
    page.set_content(HTML,wait_until='load');page.wait_for_timeout(150)
    check('Landing rendered all requested major sections',page.locator('main > section').count()==10,page.locator('main > section').count())
    check('Unknown financial values are never zeroed',page.locator('[data-metric="holders"]').inner_text()=='Not published')
    page.locator('[data-buy]').first.click()
    check('Get CRUMB opens an accessible real dialog',page.locator('#token-dialog').evaluate('(x)=>x.open') and page.get_by_role('dialog').count()==1)
    check('Prelaunch modal does not fake a swap',page.locator('#dialog-title').inner_text()=='Not quite hatched.' and page.locator('[data-external-buy]').count()==0)
    page.screenshot(path=str(OUTPUT/'token-dialog.png'))
    page.keyboard.press('Escape')
    check('Escape closes dialog and restores focus',not page.locator('#token-dialog').evaluate('(x)=>x.open') and page.locator('[data-buy]').first.evaluate('(x)=>document.activeElement===x'))
    page.locator('[data-chart]').first.click();page.wait_for_timeout(150)
    check('Missing chart gives explicit feedback', 'No verified chart' in page.locator('[data-toast-message]').inner_text(), page.locator('[data-toast-message]').inner_text())
    page.locator('[data-unannounced="x"]').first.click()
    check('Unannounced social channels never open fake accounts','not announced' in page.locator('[data-toast-message]').inner_text())
    page.locator('[data-copy-contract]').dispatch_event('click')
    check('Contract copy does not copy an invented address','No contract address' in page.locator('[data-toast-message]').inner_text())
    page.locator('[data-allocation="liquidity"]').click()
    check('Allocation selects and updates graphic','20' in page.locator('[data-allocation-figure]').inner_text() and page.locator('[data-allocation="liquidity"]').get_attribute('aria-pressed')=='true')
    check('Allocation diagram represents exactly 100 crumbs',page.locator('[data-crumb-group]').count()==100)
    check('Selected allocation highlights exactly its percentage',page.locator('.allocation-crumb.is-highlighted').count()==20)
    page.keyboard.press('ArrowDown')
    check('Tokenomics supports arrow-key navigation',page.locator('[data-allocation="marketing"]').get_attribute('aria-pressed')=='true')
    page.locator('[data-roadmap-next]').click();page.wait_for_timeout(100)
    check('Roadmap controls expand next stage',page.locator('[data-roadmap-card]').nth(1).locator('details').get_attribute('open') is not None)
    page.locator('[data-mood="rich"]').click()
    check('Gallery changes mascot and caption',page.locator('[data-featured-name]').inner_text()=='Fancy bird' and page.locator('[data-featured-art] .mood-rich').count()==1)
    with page.expect_download() as d:
        page.locator('[data-download-avatar]').click()
    download=d.value;download.save_as(str(OUTPUT/'test-avatar.svg'))
    avatar=Path(str(OUTPUT/'test-avatar.svg')).read_text()
    check('Avatar exports a self-contained SVG',download.suggested_filename=='crumb-rich-avatar.svg' and '<style>' in avatar and 'mood-rich' in avatar and '<script' not in avatar, len(avatar))
    page.locator('[data-like]').click()
    check('Meme reaction toggle has accessible pressed state',page.locator('[data-like]').get_attribute('aria-pressed')=='true')
    with page.expect_download() as d:
        page.locator('[data-download-poster="coo"]').click()
    download=d.value;download.save_as(str(OUTPUT/'test-meme.svg'))
    check('Meme download produces actual SVG',download.suggested_filename=='crumb-coo-meme.svg')
    page.locator('[data-hero-mascot]').click()
    check('Mascot responds to clicks',page.locator('[data-bird-speech]').inner_text()=='a crumb? for me?')
    check('Reduced motion is respected',page.locator('html').evaluate('(x)=>x.classList.contains("motion-paused")'))
    page.emulate_media(reduced_motion='no-preference');page.wait_for_timeout(200)
    page.locator('[data-motion-toggle]').click()
    check('Manual pause pauses animations',page.locator('html').evaluate('(x)=>x.classList.contains("motion-paused")'))
    page.locator('[data-motion-toggle]').click()
    check('Manual resume works',not page.locator('html').evaluate('(x)=>x.classList.contains("motion-paused")'))
    page.emulate_media(reduced_motion='reduce')
    for width in [320,360,375,390,430,700,768,1024,1440,1920]:
        page.set_viewport_size({'width':width,'height':900});page.wait_for_timeout(30)
        d=page.evaluate('''()=>({client:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth})''')
        check(f'No page-level horizontal overflow at {width}px',d['scroll']<=width,d)
    page.set_viewport_size({'width':390,'height':844});page.evaluate('scrollTo(0,0)');page.wait_for_timeout(50)
    page.locator('[data-menu-toggle]').click()
    check('Mobile menu opens',page.locator('[data-menu-toggle]').get_attribute('aria-expanded')=='true' and not page.locator('#mobile-menu').evaluate('(x)=>x.hidden'))
    page.keyboard.press('Escape')
    check('Mobile menu closes with Escape',page.locator('[data-menu-toggle]').get_attribute('aria-expanded')=='false')
    check('No runtime JavaScript errors',not errors,errors)
    browser.close()
Path(str(OUTPUT/'results.json')).write_text(json.dumps(results,indent=2))
print('SUMMARY',sum(r['passed'] for r in results),'/',len(results))

raise SystemExit(0 if all(result['passed'] for result in results) else 1)
